add_rules("mode.debug", "mode.release")
set_optimize("fastest")
add_defines("VERSION=\"v$(env VERSION)\"", "LOG_USE_COLOR")

target("log")
    set_kind("shared")
    add_files("log.c")

target("cJSON")
    set_kind("static")
    add_files("cJSON.cpp")
    on_install(function (target)
    end)
    on_uninstall(function (target)
    end)
