add_rules("mode.debug", "mode.release")
set_optimize("fastest")
add_ldflags("-ldl")
add_defines("VERSION=\"v$(env VERSION)\"", "LOG_USE_COLOR")

target("log")
    set_kind("shared")
    add_files("log.c")

target("deps")
    set_kind("static")
    add_syslinks("pthread")
    add_files("bindthread.cpp", "module.cpp")
    on_install(function (target)
    end)
    on_uninstall(function (target)
    end)

target("cJSON")
    set_kind("static")
    add_files("cJSON.cpp")
    on_install(function (target)
    end)
    on_uninstall(function (target)
    end)

target("extrapid")
    set_kind("binary")
    add_deps("log", "deps")
    add_syslinks("pthread")
    add_linkdirs("$(buildir)/")
    add_rpathdirs("@loader_path/lib")
    add_files("main.cpp")
    on_install(function (target)                         end)                                                 on_uninstall(function (target)                       end)
