name: Test commit and pr

on:
  pull_request:
  push:

jobs:

  build-with-gcc:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev

      - name: Install deps
        run: sudo apt update && sudo apt-get install manpages-posix-dev glibc-doc manpages-posix build-essential -y

      - name: Pull submodule
        run: git submodule update --init --recursive

      - name: Build with xmake
        run: xmake f --cc=gcc --cxx=g++ -y && xmake build -y
      
  build-with-clang:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@dev
      
      - name: Install deps
        run: sudo apt update && sudo apt-get install manpages-posix-dev glibc-doc manpages-posix build-essential clang -y

      - name: Pull submodule
        run: git submodule update --init --recursive

      - name: Build with xmake
        run: xmake f --cc=clang --cxx=clang++ -y && xmake build -y

